version: "3.8"
services:
  app:
    build:
      context: ./src
      dockerfile: Dockerfile
    volumes:
      - /Users/tilman/Movies/bbb:/var/bigbluebutton/published/presentation
      - ./tmp:/home/bigbluebutton/tmp
    security_opt:
      - seccomp:"./chrome.json"